using System;
using System.Collections.Generic;
using CatNo = ChaListDefine.CategoryNo;
using Ktype = ChaListDefine.KeyType;

namespace SardineTail
{
    internal static partial class CategoryNoExtensions {
        static Tuple<CatNo, IEnumerable<KeyTypeCollector>> Collectors(CatNo item) => 
            new (item, item switch {
                CatNo.ao_arm => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_wrist_L"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5/6"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_body => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_back"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/5/6/7"),
                    new Text(Ktype.Detail, "1"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_face => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_megane"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5/6/7/11"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_hair => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_hair_pin"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5/6/7/11"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_hand => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_ind_L"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5/6/9/11"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_head => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_hair_twin_L"),
                    new Text(Ktype.HideHair, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/4"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_kokan => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata_01"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_kokan"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "5"),
                    new Text(Ktype.Attribute, "99"),
                    new Text(Ktype.Detail, "1"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_leg => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_leg_L"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/4/11"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_neck => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_bust"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5/6/7/9/11"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.ao_waist => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.Parent, "a_n_waist_b"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "99"),
                    new Text(Ktype.Detail, "0"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.bo_body => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ShapeAnimeAB, Plugin.AssetBundle),
                    new Asset(Ktype.ShapeAnime),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex)
                ],
                CatNo.bo_hair_b => [
                    new Text(Ktype.Kind, "1"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.SetHair, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1"),
                    new Text(Ktype.Detail, "0/4"),
                ],
                CatNo.bo_hair_f => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5"),
                    new Text(Ktype.Detail, "0/1/2/3/4/5"),
                ],
                CatNo.bo_hair_o => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5"),
                    new Text(Ktype.Detail, "0/1/2/3/4/5"),
                ],
                CatNo.bo_hair_s => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5"),
                    new Text(Ktype.Detail, "0/3/4/5"),
                ],
                CatNo.bo_head => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ShapeAnimeAB, Plugin.AssetBundle),
                    new Asset(Ktype.ShapeAnime),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Preset)
                ],
                CatNo.bo_nail => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.bo_nail_leg => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.co_bot => [
                    new Text(Ktype.Kind, "4"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.Coordinate, "0"),
                    new Text(Ktype.HideShorts, "1"),
                    new Text(Ktype.NoShake, "0"),
                    new Text(Ktype.SkirtType, "0"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.OverTopMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverTopMask, "0"),
                    new Text(Ktype.OverBotMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverBotMask, "0"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.MainTex03AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex03, "0"),
                    new Text(Ktype.ColorMask03AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask03Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.KokanHide, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2"),
                    new Text(Ktype.Attribute, "0/3"),
                    new Text(Ktype.Detail, "0/1/2/3")
                ],
                CatNo.co_bra => [
                    new Text(Ktype.Kind, "1"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.NormalData, "0"),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.Coordinate, "0"),
                    new Text(Ktype.MabUV, "0"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.OverTopMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverTopMask, "0"),
                    new Text(Ktype.OverBotMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverBotMask, "0"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.NipHide, "1"),
                    new Text(Ktype.KokanHide, "0"),
                    new Text(Ktype.HalfUndress, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/3"),
                    new Text(Ktype.Detail, "0/1/2/3"),
                    new Text(Ktype.Sort, "0")
                ],
                CatNo.co_gloves => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.NailHide, "1"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0"),
                ],
                CatNo.co_panst => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata005_00"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.KokanHide, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "99"),
                    new Text(Ktype.Attribute, "99"),
                    new Text(Ktype.Detail, "0/1/2/3")
                ],
                CatNo.co_shoes => [
                    new Text(Ktype.Kind, "1"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.ShoesType, "1"),
                    new Text(Ktype.Sex, "1"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0/1/2/3"),
                ],
                CatNo.co_shorts => [
                    new Text(Ktype.Kind, "1"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "0"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.OverTopMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverTopMask, "0"),
                    new Text(Ktype.OverBotMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverBotMask, "0"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.KokanHide, "1"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/3"),
                    new Text(Ktype.Detail, "0/1/2/3/4"),
                    new Text(Ktype.Sort, "5"),
                ],
                CatNo.co_socks => [
                    new Text(Ktype.Kind, "1"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.StateType, "1"),
                    new Text(Ktype.SocksDent, "0"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.DentTexAB, Plugin.AssetBundle),
                    new Image(Ktype.DentTex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/5/6"),
                    new Text(Ktype.Detail, "0/1/2/3"),
                ],
                CatNo.co_top => [
                    new Text(Ktype.Kind, "4"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainManifest, "abdata"),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Asset(Ktype.MainData),
                    new Text(Ktype.NormalData, "0"),
                    new Text(Ktype.StateType, "0"),
                    new Text(Ktype.NotBra, "0"),
                    new Text(Ktype.NoShake, "0"),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.OverTopMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverTopMask, "0"),
                    new Text(Ktype.OverBotMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.OverBotMask, "0"),
                    new Text(Ktype.MainTexAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ColorMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.MainTex02AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex02, "0"),
                    new Text(Ktype.ColorMask02AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask02Tex, "0"),
                    new Text(Ktype.MainTex03AB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex03, "0"),
                    new Text(Ktype.ColorMask03AB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMask03Tex, "0"),
                    new Text(Ktype.PaintMaskAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintMask, "0"),
                    new Text(Ktype.NipHide, "1"),
                    new Text(Ktype.KokanHide, "0"),
                    new Text(Ktype.HalfUndress, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/3"),
                    new Text(Ktype.Detail, "0/1/3"),
                    new Text(Ktype.Sort, "5"),
                ],
                CatNo.bodypaint_layout => [
                    new Text(Ktype.Kind, "0"),
                    new Name(),
                    new Text(Ktype.PosX),
                    new Text(Ktype.PosY),
                    new Text(Ktype.Rot, "0"),
                    new Text(Ktype.Scale, "-4"),
                    new Text(Ktype.CenterX, "0"),
                    new Text(Ktype.MoveX, "0"),
                    new Text(Ktype.CenterY, "0"),
                    new Text(Ktype.MoveY, "0"),
                    new Text(Ktype.CenterScale, "-4"),
                    new Text(Ktype.AddScale, "4.5"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na")
                ],
                CatNo.facepaint_layout => [
                    new Text(Ktype.Kind, "0"),
                    new Name(),
                    new Text(Ktype.PosX),
                    new Text(Ktype.PosY),
                    new Text(Ktype.Rot, "0"),
                    new Text(Ktype.Scale, "-2.5"),
                    new Text(Ktype.CenterX, "0"),
                    new Text(Ktype.MoveX, "0"),
                    new Text(Ktype.CenterY, "0"),
                    new Text(Ktype.MoveY, "0"),
                    new Text(Ktype.CenterScale, "-2.5"),
                    new Text(Ktype.AddScale, "3"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na")
                ],
                CatNo.mole_layout => [
                    new Text(Ktype.Kind, "0"),
                    new Name(),
                    new Text(Ktype.PosX),
                    new Text(Ktype.PosY),
                    new Text(Ktype.Rot, "0"),
                    new Text(Ktype.Scale, "-0.8"),
                    new Text(Ktype.CenterX, "0"),
                    new Text(Ktype.MoveX, "0"),
                    new Text(Ktype.CenterY, "0"),
                    new Text(Ktype.MoveY, "0"),
                    new Text(Ktype.CenterScale, "-0.8"),
                    new Text(Ktype.AddScale, "1"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na")
                ],
                CatNo.mt_face_detail => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.NormallMapDetail, "0"),
                    new Image(Ktype.LineMask),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "99"),
                    new Text(Ktype.Attribute, "99"),
                    new Text(Ktype.Detail, "99")
                ],
                CatNo.mt_eyeshadow => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyeshadowTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_cheek => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.CheekTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2"),
                    new Text(Ktype.Detail, "0"),
                ],
                CatNo.mt_lip => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.LipTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "1/2/3/4/5"),
                    new Text(Ktype.Attribute, "2/3"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_lipline => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.LiplineTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "1/2/3/4"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_face_paint => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_body_paint => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.PaintTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eyebrow => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyebrowTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eye_white => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyeWhiteTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0"),
                ],
                CatNo.mt_eye => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyeTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0"),
                ],
                CatNo.mt_eye_gradation => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.ColorMaskTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eye_hi_up => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyeHiUpTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0"),
                ],
                CatNo.mt_eyeline_up => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyelineUpTex),
                    new Image(Ktype.EyelineShadowTex, "0"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eyeline_down => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyelineDownTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_nose => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.NoseTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_mole => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.MoleTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.MoleLayoutID, "0"),
                    new Text(Ktype.Image, "99"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eyepipil => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyepipilTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_eyelid => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.EyelidTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_body_detail => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.NormallMapDetail),
                    new Image(Ktype.LineMask),
                    new Text(Ktype.Sex, "3"),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_sunburn => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.SunburnTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "1"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_nip => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.NipTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_underhair => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.UnderhairTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_pattern => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0"),
                    new Text(Ktype.Attribute, "0"),
                    new Text(Ktype.Detail, "0")
                ],
                CatNo.mt_hairgloss => [
                    new Text(Ktype.Kind, "0"),
                    new Text(Ktype.Possess, "1"),
                    new Name(),
                    new Text(Ktype.MainAB, Plugin.AssetBundle),
                    new Image(Ktype.MainTex),
                    new Text(Ktype.ThumbAB, Plugin.AssetBundle),
                    new Image(Ktype.ThumbTex, "thumb_na"),
                    new Text(Ktype.Image, "0/1/2/3/4/5"),
                    new Text(Ktype.Attribute, "0/1/2/3/4/5"),
                    new Text(Ktype.Detail, "0/1/2/3/4/5")
                ],
                _ => []
            });
    }
}
 